// <auto-generated />
namespace Mvc4Windsor.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddTarefa : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddTarefa));
        
        string IMigrationMetadata.Id
        {
            get { return "201302181804018_AddTarefa"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
